version: '3.2'

networks:
  unreliable-net:

services:
  athensdb_1:
    build: ../
    hostname: athensdb_1
    ports:
      - 9080:9080
    links:
      - athensdb_2
      - athensdb_3
    environment:
      PEERS: athensdb_2,athensdb_3
    command:
      - '-log.level=debug'
    networks:
      - unreliable-net
  athensdb_2:
    build: ../
    hostname: athensdb_2
    ports:
      - 9081:9080
    command:
      - '-log.level=debug'
    networks:
      - unreliable-net
  athensdb_3:
    build: ../
    hostname: athensdb_3
    ports:
      - 9082:9080
    environment:
      PEERS: athensdb_1,athensdb_3
    command:
      - '-log.level=debug'
    networks:
      - unreliable-net
  prometheus:
    image: prom/prometheus:v1.7.1
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.engine=none'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - load_balancer
    environment:
      PEERS: athensdb_1,athensdb_2
    networks:
      - unreliable-net
  load_balancer:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - athensdb_1
      - athensdb_2
      - athensdb_3
    networks:
      - unreliable-net
  integration-tests:
    build:
      context: ../
      dockerfile: integration_tests/Dockerfile
    links:
      - athensdb_1
      - athensdb_2
      - athensdb_3
      - load_balancer
    networks:
      - unreliable-net
  gremlins-fault-injection:
    image: qualimente/gremlins
    volumes:
      - ./profiles:/app/gremlins/profiles
    command: gremlins -m gremlins.profiles.faulty -p faulty.profile
    pid: host # FIXME: really?
    network_mode: "service:athensdb_1"
    cap_add:
      - NET_ADMIN
